[package]
name = "civilization"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.test]
# opt-level = 3

[dependencies]
gl = "0.10.0"
glfw = "0.23.0"